package com.aem.pokebootcamp.core.config;

import org.osgi.service.metatype.annotations.ObjectClassDefinition;
import org.osgi.service.metatype.annotations.AttributeDefinition;

/**
 * Defines the configuration for the Page Creation Scheduler in AEM.
 * This configuration is used to trigger page creation jobs based on the
 * specified parameters and scheduling frequency.
 */
@ObjectClassDefinition(
        name = "AEM Bootcamp Page Creation Scheduler",
        description = "Triggers page creation jobs on a configurable schedule"
)
public @interface PageCreationSchedulerConfig {

    /**
     * Retrieves the starting ID for generating Pokemon pages.
     * This value defines the first Pokemon ID for which a page will be created
     * during the execution of the scheduling job.
     *
     * @return the starting Pokemon ID as an integer
     */
    @AttributeDefinition(
            name = "Start ID",
            description = "Starting Pokemon ID"
    )
    int startId() default 1;

    /**
     * Retrieves the ending Pokemon ID for generating pages.
     * This value defines the last Pokemon ID for which a page will be created
     * during the execution of the scheduling job.
     *
     * @return the ending Pokemon ID as an integer
     */
    @AttributeDefinition(
            name = "End ID",
            description = "Ending Pokemon ID"
    )
    int endId() default 10;

    /**
     * Retrieves the target path where pages will be created.
     * This value specifies the parent path under which the pages
     * dynamically generated by the scheduler will be stored.
     *
     * @return the target path as a string
     */
    @AttributeDefinition(
            name = "Target Path",
            description = "Parent path where pages will be created"
    )
    String targetPath() default "/content/aempokebootcamp/us/en/pokemons";

    /**
     * Retrieves the CRON expression that defines the frequency of the scheduler execution.
     * The CRON expression follows the standard format for specifying schedule intervals.
     *
     * @return the CRON expression as a string
     */
    @AttributeDefinition(
            name = "CRON Expression",
            description = "CRON expression defining scheduler frequency"
    )
    String schedulerExpression() default "0 * * * * ?";
}
